language: node_js # Node runs `npm install` and `npm test` automatically
node_js:
  - node # Uses the latest version (via nvm)
sudo: false # Allows Travis to run this project in container
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
